FROM vyahello/jenkins-base:0.1.0
LABEL version=3.6 \
      metadata="The main image for Jenkins app with python3.6" \
      maintainer="Volodymyr Yahello <vyahello@gmail.com>"
USER root
RUN wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz && \
    tar xzf Python-3.6.5.tgz && \
    cd Python-3.6.5 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    ln -s /usr/local/bin/python3.6 /usr/bin/python && \
    ln -s /usr/local/bin/pip3.6 /usr/bin/pip
