name: Build and Verify python3.10 image
on:
  push:
    branches:
      - 'master'
jobs:
  build_and_verify_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile-python3.10
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jenkins-python:test
      - name: Verify image
        run: |
          docker run --rm --user root ${{ secrets.DOCKER_HUB_USERNAME }}/jenkins-python:test python -V | grep "Python 3.10.0"
          docker run --rm --user root ${{ secrets.DOCKER_HUB_USERNAME }}/jenkins-python:test pip -V | grep "python 3.10"
